CREATE TABLE llx_lmdbzoning_profile_zone (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_profile integer NOT NULL,
	zone_code varchar(64) NOT NULL,
	label varchar(255) NOT NULL,
	distance_min double DEFAULT 0 NOT NULL,
	distance_max double,
	priority integer DEFAULT 0 NOT NULL,
	fk_categorie_default integer,
	fk_categorie_powerplantpv integer,
	fk_categorie_propal integer,
	fk_categorie_commande integer,
	fk_categorie_contract integer,
	fk_categorie_project integer,
	fk_categorie_fichinter integer,
	fk_categorie_timesheetweek integer,
	active tinyint DEFAULT 1 NOT NULL,
	datec datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer,
	fk_user_modif integer,
	import_key varchar(14)
) ENGINE=innodb;
