CREATE TABLE llx_lmdbzoning_object_zone (
	rowid integer AUTO_INCREMENT PRIMARY KEY,
	entity integer DEFAULT 1 NOT NULL,
	fk_profile integer NOT NULL,
	fk_referencepoint integer NOT NULL,
	element_type varchar(64) NOT NULL,
	fk_element integer NOT NULL,
	address_hash varchar(64),
	address_raw text,
	latitude double,
	longitude double,
	distance_km double,
	calculated_zone_code varchar(64),
	calculated_fk_zone integer,
	zone_code varchar(64),
	fk_zone integer,
	fk_categorie integer,
	calculation_status varchar(32) NOT NULL,
	calculation_message text,
	manual_override tinyint DEFAULT 0 NOT NULL,
	override_reason text,
	date_calculation datetime,
	fk_user_calculation integer,
	date_override datetime,
	fk_user_override integer,
	datec datetime,
	tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	fk_user_creat integer,
	fk_user_modif integer,
	import_key varchar(14)
) ENGINE=innodb;
